package top.kid297.alipaypayment.model;

import lombok.Data;

@Data
public class TsOrder {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ts_order.ORDERID
     * @mbggenerated  Thu Nov 30 16:12:04 CST 2017
     */
    private Integer orderid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ts_order.ORDERNO
     * @mbggenerated  Thu Nov 30 16:12:04 CST 2017
     */
    private String orderno;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ts_order.USERID
     * @mbggenerated  Thu Nov 30 16:12:04 CST 2017
     */
    private Integer userid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ts_order.USERNAME
     * @mbggenerated  Thu Nov 30 16:12:04 CST 2017
     */
    private String username;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ts_order.COMPANYID
     * @mbggenerated  Thu Nov 30 16:12:04 CST 2017
     */
    private Integer companyid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ts_order.COMPANYNAME
     * @mbggenerated  Thu Nov 30 16:12:04 CST 2017
     */
    private String companyname;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ts_order.PAY_PRICE
     * @mbggenerated  Thu Nov 30 16:12:04 CST 2017
     */
    private Float payPrice;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ts_order.CRTIME
     * @mbggenerated  Thu Nov 30 16:12:04 CST 2017
     */
    private String crtime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ts_order.TIME_LONG
     * @mbggenerated  Thu Nov 30 16:12:04 CST 2017
     */
    private String timeLong;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ts_order.PAY_TYPE
     * @mbggenerated  Thu Nov 30 16:12:04 CST 2017
     */
    private String payType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ts_order.PAY_TYPE_DIS
     * @mbggenerated  Thu Nov 30 16:12:04 CST 2017
     */
    private String payTypeDis;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ts_order.PAY_STATE
     * @mbggenerated  Thu Nov 30 16:12:04 CST 2017
     */
    private String payState;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ts_order.ISBILLING
     * @mbggenerated  Thu Nov 30 16:12:04 CST 2017
     */
    private String isbilling;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ts_order.INVOICE_TYPE
     * @mbggenerated  Thu Nov 30 16:12:04 CST 2017
     */
    private String invoiceType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ts_order.ENDTIME
     * @mbggenerated  Thu Nov 30 16:12:04 CST 2017
     */
    private String endtime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ts_order.MEMBER_PRICE_ID
     * @mbggenerated  Thu Nov 30 16:12:04 CST 2017
     */
    private Integer memberPriceId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ts_order.MEMBER_TYPE
     * @mbggenerated  Thu Nov 30 16:12:04 CST 2017
     */
    private String memberType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ts_order.TRADE_NO
     * @mbggenerated  Thu Nov 30 16:12:04 CST 2017
     */
    private String tradeNo;
}
