jedis :
  pool :
    host : 127.0.0.1
    port : 6379
    config :
      #最大活动对象数
      maxTotal: 10
      #最大能够保持idel状态的对象数
      maxIdle: 10
      #最小能够保持idel状态的对象数
      minIdle: 50
      #当池内没有返回对象时，最大等待时间
      maxWaitMillis : 100000
      #当调用borrow Object方法时，是否进行有效性检查
      testOnBorrow: true
      #当调用return Object方法时，是否进行有效性检查
      testOnReturn: true
      #“空闲链接”检测线程，检测的周期，毫秒数。如果为负值，表示不运行“检测线程”。默认为-1.
      timeBetweenEvictionRunsMillis: 30000
      #向调用者输出“链接”对象时，是否检测它的空闲超时；
      testWhileIdle: true
      # 对于“空闲链接”检测线程而言，每次检测的链接资源的个数。默认为3.
      numTestsPerEvictionRun: 50

      #其中JedisPoolConfig对一些参数的默认设置如下：
      #testWhileIdle: true
      #minEvictableIdleTimeMills: 60000
      #timeBetweenEvictionRunsMillis: 30000
      #numTestsPerEvictionRun: -1